#pragma once

#ifndef _MITOKENBLE_UUIDS_H_
#define _MITOKENBLE_UUIDS_H_

//Services
#define BLE_UUID_SERVICE_DEVICE_INFO		0x180A
#define BLE_UUID_SERVICE_PUSH_BUTTON		0xFFE0
#define BLE_UUID_SERVICE_SYSTEM_CONFIG		0xA500
#define BLE_UUID_SERVICE_SECURE_BOND		0xA200
#define BLE_UUID_SERVICE_AUTHENTICATION		0xA400
#define BLE_UUID_SERVICE_USER_KEY			0xA300

#define BLE_UUID_SERVICE_HASH_OLD			0xA400
#define BLE_UUID_SERVICE_HASH				0xA700

#define BLE_UUID_SERVICE_SECRET				0xA600
#define BLE_UUID_SERVICE_OATH				0xA000

//Attributes
#define BLE_UUID_ATTRIBUTE_DEVICE_INFO_SYSTEM_ID				0x2A23
#define BLE_UUID_ATTRIBUTE_DEVICE_INFO_FIRMWARE_VERSION			0x2A26
#define BLE_UUID_ATTRIBUTE_DEVICE_INFO_HARDWARE_VERSION			0x2A27

#define BLE_UUID_ATTRIBUTE_PUSH_BUTTON_BUTTON_PRESSED			0xFFE1
#define BLE_UUID_ATTRIBUTE_PUSH_BUTTON_CHARACTERISTIC_CONFIG	0x2902

#define BLE_UUID_ATTRIBUTE_SYSTEM_CONFIG_BUFFER					0xA501
#define BLE_UUID_ATTRIBUTE_SYSTEM_CONFIG_ENCRYPTOR				0xA502

#define BLE_UUID_ATTRIBUTE_SECURE_BOND_STATUS					0xA201
#define BLE_UUID_ATTRIBUTE_SECURE_BOND_PUBLIC_KEY				0xA202
#define BLE_UUID_ATTRIBUTE_SECURE_BOND_VERIFICATION_BUFFER		0xA203
#define BLE_UUID_ATTRIBUTE_SECURE_BOND_CONFIG					0xA204
#define BLE_UUID_ATTRIBUTE_SECURE_BOND_ENCRYPT_CONFIG			0xA205

#define BLE_UUID_ATTRIBUTE_AUTHENTICATION_MODE					0xA401
#define BLE_UUID_ATTRIBUTE_AUTHENTICATION_STATUS				0xA402
#define BLE_UUID_ATTRIBUTE_AUTHENTICATION_BUFFER				0xA403


#define BLE_UUID_ATTRIBUTE_USER_KEY_BUFFER						0xA301

#define BLE_UUID_ATTRIBUTE_HASH_STATUS_OLD						0xA401
#define BLE_UUID_ATTRIBUTE_HASH_BUFFER_OLD						0xA402

#define BLE_UUID_ATTRIBUTE_HASH_STATUS							0xA701
#define BLE_UUID_ATTRIBUTE_HASH_BUFFER							0xA702


#define BLE_UUID_ATTRIBUTE_HASH_STATUS_OLD						0xA401
#define BLE_UUID_ATTRIBUTE_HASH_BUFFER_OLD						0xA402


#define BLE_UUID_ATTRIBUTE_SECRET_BUFFER						0xA601

#define BLE_UUID_ATTRIBUTE_OATH_HOTP_BUFFER						0xA001
#define BLE_UUID_ATTRIBUTE_OATH_HOTP_DIGITS						0xA002
#define BLE_UUID_ATTRIBUTE_OATH_HOTP_KEY_SOURCE					0xA003

#endif