#define MITOKEN_VERSION_MAJOR	4
#define MITOKEN_VERSION_MINOR	3
#define MITOKEN_VERSION_BUILD	8075
#define MITOKEN_VERSION_REVISION	0
#define MITOKEN_PRODUCT	Version 4.3.9.4, build 8075.072534eca6d8

#define MITOKEN_VERSION MITOKEN_VERSION_MAJOR##,##MITOKEN_VERSION_MINOR##,##MITOKEN_VERSION_BUILD##,##MITOKEN_VERSION_REVISION
#define MITOKEN_VERSION_DOTS MITOKEN_VERSION_MAJOR##.##MITOKEN_VERSION_MINOR##.##MITOKEN_VERSION_BUILD##.##MITOKEN_VERSION_REVISION
#define QUOTE_(x) #x
#define QUOTE(x) QUOTE_(x)
